export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const PASSWORD_FORGET = '/password-forget';
export const ADMIN = '/admin';
export const ADMIN_DETAILS = '/admin/:id';

export const ADMINPLACES = '/AdminPlaces';
export const ADMINPLACES_DETAILS = '/AdminPlaces/:id';
export const ADDPLACE = '/addPlace';
export const PROFILE = '/profile';
export const HOME_DETAILS = '/home/:id';
export const SETTINGS = '/settings';
export const WELCOME = '/welcome';
export const ADMINISTRATION = '/Administration';
export const EXPLORE = '/Explore';
export const LEGAL='/Terms-and-conditions'